security:
  basic:
    enabled: false

management:
  security:
    enabled: false
    
server:
  port: 8082
  
eureka:
  instance:
    nonSecurePort: ${server.port:8082}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/  